//Next
import type { Metadata } from "next"
//Fonts
import { Anton, Great_Vibes } from "next/font/google"
//Styles
import "./globals.css"
//Components
import NavBar from "@/components/global/NavBar"

const antonSans = Anton({
  variable: "--font-anton-sans",
  subsets: ["latin"],
  weight: "400",
})

const greatVibes = Great_Vibes({
  variable: "--font-great-vibes",
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Flaming Pizza",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${antonSans.variable} ${greatVibes.variable} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
